// Generated by scripts/i18n-namespaces.mjs. Do not edit by hand.
import type analytics from './locales/en/analytics.json';
import type app from './locales/en/app.json';
import type browser from './locales/en/browser.json';
import type card from './locales/en/card.json';
import type chat from './locales/en/chat.json';
import type citation from './locales/en/citation.json';
import type cmd from './locales/en/cmd.json';
import type common from './locales/en/common.json';
import type companion from './locales/en/companion.json';
import type errorBoundary from './locales/en/errorBoundary.json';
import type evidence from './locales/en/evidence.json';
import type knowledge from './locales/en/knowledge.json';
import type live from './locales/en/live.json';
import type media from './locales/en/media.json';
import type nav from './locales/en/nav.json';
import type preview from './locales/en/preview.json';
import type project from './locales/en/project.json';
import type providers from './locales/en/providers.json';
import type search from './locales/en/search.json';
import type settings from './locales/en/settings.json';
import type shortcuts from './locales/en/shortcuts.json';
import type sidebar from './locales/en/sidebar.json';
import type sources from './locales/en/sources.json';
import type taskCenter from './locales/en/taskCenter.json';
import type themeStudio from './locales/en/themeStudio.json';
import type time from './locales/en/time.json';
import type tray from './locales/en/tray.json';
import type update from './locales/en/update.json';
import type usage from './locales/en/usage.json';
import type voice from './locales/en/voice.json';
import type welcome from './locales/en/welcome.json';
import type wizard from './locales/en/wizard.json';
import type workflows from './locales/en/workflows.json';

export const locales = [
  'zh-CN',
  'en',
  'ja',
  'ko',
  'zh-TW',
  'fr',
  'de',
  'es',
  'pt',
  'ru',
] as const;

export type Locale = (typeof locales)[number];

export const translationNamespaces = [
  'analytics',
  'app',
  'browser',
  'card',
  'chat',
  'citation',
  'cmd',
  'common',
  'companion',
  'errorBoundary',
  'evidence',
  'knowledge',
  'live',
  'media',
  'nav',
  'preview',
  'project',
  'providers',
  'search',
  'settings',
  'shortcuts',
  'sidebar',
  'sources',
  'taskCenter',
  'themeStudio',
  'time',
  'tray',
  'update',
  'usage',
  'voice',
  'welcome',
  'wizard',
  'workflows',
] as const;

export type TranslationNamespace = (typeof translationNamespaces)[number];

type NamespaceKeyMap = {
  analytics: typeof analytics;
  app: typeof app;
  browser: typeof browser;
  card: typeof card;
  chat: typeof chat;
  citation: typeof citation;
  cmd: typeof cmd;
  common: typeof common;
  companion: typeof companion;
  errorBoundary: typeof errorBoundary;
  evidence: typeof evidence;
  knowledge: typeof knowledge;
  live: typeof live;
  media: typeof media;
  nav: typeof nav;
  preview: typeof preview;
  project: typeof project;
  providers: typeof providers;
  search: typeof search;
  settings: typeof settings;
  shortcuts: typeof shortcuts;
  sidebar: typeof sidebar;
  sources: typeof sources;
  taskCenter: typeof taskCenter;
  themeStudio: typeof themeStudio;
  time: typeof time;
  tray: typeof tray;
  update: typeof update;
  usage: typeof usage;
  voice: typeof voice;
  welcome: typeof welcome;
  wizard: typeof wizard;
  workflows: typeof workflows;
};

type NamespacedKey<Namespace extends string, Key extends string> = `${Namespace}.${Key}`;

export type TranslationKey = {
  [Namespace in keyof NamespaceKeyMap]: NamespacedKey<
    Extract<Namespace, string>,
    Extract<keyof NamespaceKeyMap[Namespace], string>
  >;
}[keyof NamespaceKeyMap];

export type TranslationKeys = Record<TranslationKey, string>;
