// Generated by scripts/i18n-namespaces.mjs. Do not edit by hand.
import { flattenTranslationNamespaces } from '../../namespace';
import type { TranslationKeys } from '../../types';
import analytics from './analytics.json';
import app from './app.json';
import browser from './browser.json';
import card from './card.json';
import chat from './chat.json';
import citation from './citation.json';
import cmd from './cmd.json';
import common from './common.json';
import companion from './companion.json';
import errorBoundary from './errorBoundary.json';
import evidence from './evidence.json';
import knowledge from './knowledge.json';
import live from './live.json';
import media from './media.json';
import nav from './nav.json';
import preview from './preview.json';
import project from './project.json';
import providers from './providers.json';
import remote from './remote.json';
import search from './search.json';
import settings from './settings.json';
import shortcuts from './shortcuts.json';
import sidebar from './sidebar.json';
import sources from './sources.json';
import taskCenter from './taskCenter.json';
import themeStudio from './themeStudio.json';
import time from './time.json';
import tray from './tray.json';
import update from './update.json';
import usage from './usage.json';
import voice from './voice.json';
import welcome from './welcome.json';
import wizard from './wizard.json';
import workflows from './workflows.json';

export const es: TranslationKeys = flattenTranslationNamespaces({
  analytics,
  app,
  browser,
  card,
  chat,
  citation,
  cmd,
  common,
  companion,
  errorBoundary,
  evidence,
  knowledge,
  live,
  media,
  nav,
  preview,
  project,
  providers,
  remote,
  search,
  settings,
  shortcuts,
  sidebar,
  sources,
  taskCenter,
  themeStudio,
  time,
  tray,
  update,
  usage,
  voice,
  welcome,
  wizard,
  workflows,
});
